CLIENT_CONFIG = {
    'TCP_SERVER_IP': '127.0.0.1',
    'TOMS_URL': 'http://localhost:8081',
    'WEB_SOCKET_SERVER_IP': '127.0.0.1',
    'WEB_SOCKET_SERVER_PORT': 8082,

    'INITIAL_ENTRYPOINT_POS': 80,
    'RECOVERY_ENTRYPOINT_POS': 20,
    'APPLY_PEER_CAPA': False
}

PEER_CONFIG = {
    'PEER_ESTAB_MAX_COUNT': 10,  # 사용 안함
    'PEER_ESTAB_TIMEOUT': 30,  # 사용 안함
    'MAX_PRIMARY_CONNECTION': 10,
    'MAX_INCOMING_CANDIDATE': 10,
    'MAX_OUTGOING_CANDIDATE': 10,
    'PEER_TTL': 3,
    'ESTAB_PEER_TIMEOUT': 15,
    'ESTAB_PEER_MAX_COUNT': 10,
    'PROBE_PEER_TIMEOUT': 5,
    'BROADCAST_OPERATION_ACK': False,
    'RELEASE_OPERATION_ACK': False,
    'PRINT_HEARTBEAT_LOG': False
}
